### ISSUE TITLE
Download Icons as PNG

### ISSUE THREAD

**Issue by SebastianSchuetze** [mattlag/Azure-Icon-Downloader#1]
This one is simple but great!

I would like to ask you one favor.
Could you somehow integrate a feature that allows me to download each SVG instantly as PNG.
And additionally to define somewhere the max height (or width) that the image should have?

See the screenshot as example (no design suggestion, but rather feature ;-)):

![image](https://user-images.githubusercontent.com/7256168/54945106-5a65e900-4f35-11e9-94e3-19381d44d03c.png)

**Comment by SebastianSchuetze** [comment]
You got promoted from here ;-)

https://twitter.com/SonOfDiesel/status/1110049523672334336

**Comment by mattlag** [comment]
Yes, this is a good idea!  I'll have to look into generating PNG from SVG on the client side...  Canvas maybe?

**Comment by SebastianSchuetze** [comment]
Yes canvas would be the way to go. I played around it myself before on the following site of mine:

https://webtools.razorspoint.com/

don't worry about the warning. Since I just use it for me, I didn't give anything in adding a proper certificate. But if you look at the JavaScript at the end of the page, you should see how I convert SVG into PNG of any size.
