### ISSUE TITLE
Support new icon

### ISSUE THREAD

**Issue by tsubasaxZZZ** [mattlag/Azure-Icon-Downloader#2]
I hope support new icon. Now some icon is broken.

![image](https://user-images.githubusercontent.com/3822284/66537851-fadfcb80-eb5c-11e9-850f-467fbe23300f.png)

**Comment by mattlag** [comment]
Ah yes - new icons are hitting production, with fancy gradients.  I'll start working on a fix :-)

**Comment by mattlag** [comment]
Fixed in v1.7 - published to the chrome store, may take a bit to show up there and to refresh in your extensions.
