### ISSUE TITLE
Check other MSFT sites for compatibility

### ISSUE THREAD

**Issue by mattlag** [mattlag/Azure-Icon-Downloader#7]
[adf.azure.com](http://adf.azure.com/)

[web.azuresynapse.net](http://web.azuresynapse.net/)

 

Here is a full list of portal urls

https://learn.microsoft.com/en-us/azure/azure-portal/azure-portal-safelist-urls?tabs=public-cloud#general-azure-services-and-documentation

**Comment by mattl-msft** [comment]
These sites don't work.
